// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace FluentHttp.Tests.Authenticators.OAuth2.AuthorizationHeader
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class OAuth2AuthorizationHeaderFeature : Xunit.IUseFixture<OAuth2AuthorizationHeaderFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OAuth2AuthorizationHeader.feature"
#line hidden
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OAuth2 Authorization Header", "check if OAuth2AuthorizationRequestHeaderAuthenticator\'s Authenticate method work" +
                    "s", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public virtual void SetFixture(OAuth2AuthorizationHeaderFeature.FixtureData fixtureData)
        {
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "OAuth2 Authorization Header")]
        [Xunit.TraitAttribute("Description", "Create a valid OAuth2AuthorizationRequestHeaderAuthenticator")]
        public virtual void CreateAValidOAuth2AuthorizationRequestHeaderAuthenticator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a valid OAuth2AuthorizationRequestHeaderAuthenticator", new string[] {
                        "important"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("a new FluentHttpRequest");
#line 7
 testRunner.When("AuthenticateUsing OAuth2AuthorizationRequestHeaderAuthenticator with access token" +
                    " 123");
#line 8
 testRunner.Then("header should contain Authorization");
#line 9
  testRunner.And("its value should be \"OAuth 123\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                OAuth2AuthorizationHeaderFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                OAuth2AuthorizationHeaderFeature.FeatureTearDown();
            }
        }
    }
}
#endregion
