// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace FluentHttp.Tests.QueryString
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FluentQueryStringCtorFeature : Xunit.IUseFixture<FluentQueryStringCtorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "QueryStringCtor.feature"
#line hidden
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FluentQueryString ctor", "Check if ctor assigns value correctly\nand FluentQueryString is constructed correc" +
                    "tly.", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public virtual void SetFixture(FluentQueryStringCtorFeature.FixtureData fixtureData)
        {
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "FluentQueryString ctor")]
        [Xunit.TraitAttribute("Description", "Pass querystring name and value as ctor params")]
        public virtual void PassQuerystringNameAndValueAsCtorParams()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pass querystring name and value as ctor params", new string[] {
                        "important"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("a null fluent querystring");
#line 8
 testRunner.When("I create a new fluent querystring with ctor params (\"qs-name\" and \"qs-value\")");
#line 9
  testRunner.And("I get name");
#line 10
  testRunner.And("I get value");
#line 11
 testRunner.Then("there should be no exception thrown");
#line 12
  testRunner.And("name should be \"qs-name\"");
#line 13
  testRunner.And("value should be \"qs-value\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "FluentQueryString ctor")]
        [Xunit.TraitAttribute("Description", "Pass querystring name as null")]
        public virtual void PassQuerystringNameAsNull()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pass querystring name as null", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("a null fluent querystring");
#line 18
 testRunner.When("I create a new fluent querystring with querystring name as null");
#line 19
 testRunner.Then("it should throw ArgumentOutOfRangeException");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "FluentQueryString ctor")]
        [Xunit.TraitAttribute("Description", "Pass querystring as string.Empty")]
        public virtual void PassQuerystringAsString_Empty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pass querystring as string.Empty", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("a null fluent querystring");
#line 23
 testRunner.When("I create a new fluent querystring with querystring name as string.Empty");
#line 24
 testRunner.Then("it should throw ArgumentOutOfRangeException");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "FluentQueryString ctor")]
        [Xunit.TraitAttribute("Description", "Pass querystring as \"\"")]
        public virtual void PassQuerystringAs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pass querystring as \"\"", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("a null fluent querystring");
#line 28
 testRunner.When("I create a new fluent querystring with querystring name as \"\"");
#line 29
 testRunner.Then("it should throw ArgumentOutOfRangeException");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "FluentQueryString ctor")]
        [Xunit.TraitAttribute("Description", "Pass querystring as white space.")]
        public virtual void PassQuerystringAsWhiteSpace_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pass querystring as white space.", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("a null fluent querystring");
#line 33
 testRunner.When("I create a new fluent querystring with querystring name as \" \"");
#line 34
 testRunner.Then("it should throw ArgumentOutOfRangeException");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                FluentQueryStringCtorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                FluentQueryStringCtorFeature.FeatureTearDown();
            }
        }
    }
}
#endregion
